name: Go

on:
  push:
    branches: [ main ]
    paths-ignore: [ dist ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ dist ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go SDK
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build/Test/Doc
      run: make
