name: Go

on:
  push:
    branches: [ main ]
    paths-ignore: [ dist ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ dist ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go SDK
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build/Test/Doc
      run: make

    - name: Zip Up Build
      uses: papeloto/action-zip@v1
      with:
        files: bin/
        dest: mssql-launcher.zip

    - name: Push Distribution
      run: |
        mkdir -p dist
        mv mssql-launcher.zip dist/mssql-launcher.zip
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add -A dist
        git commit -m "Updated distribution."
        git push github ${GITHUB_REF}

git commit -m "Update native model"
git push github HEAD:${GITHUB_REF}
